### ISSUE TITLE
something about soft-body collision 

### ISSUE THREAD

**Issue by CugAgo** [InfinyTech3D/SofaUnity-Renderer#10]
I noticed in readme “This version allows only to change the Gravity and the TimeStep of the SOFA simulation and only the VisualModel are mapped into Unity3D”
So if I want to implement collision detection between softbody and other Gameobjects in Unity, do I need to use full integration of SOFA？

**Comment by epernod** [comment]
Hi,
yes exactly for the moment. 
You can have a look here:  https://infinytech3d.com/examples/

Best regards
