### ISSUE TITLE
What does the step: "Copy the SOFA dll libraries inside" means?

### ISSUE THREAD

**Issue by CugAgo** [InfinyTech3D/SofaUnity-Renderer#6]
I don't know what should be done specifically in this step：
Copy the SOFA dll libraries inside: /myUnityProject/Assets/SofaUnity/Plugins/Native/x64 (for windows)
is this mean copy all the files with the extension .dll in sofa install path and paste it into the above path?

**Comment by epernod** [comment]
Hi @CugAgo,

thank you for your feedback and sorry if this step is not clear:
- You need to download the release v22.12 of SOFA (either using the installer of the zip file provided here: https://github.com/sofa-framework/sofa/releases/download/v23.06.00/SOFA_v23.06.00_Win64.zip
- Then you copy the content of the folder SOFA_v23.06.00_Win64\bin\ inside the folder /myUnityProject/Assets/SofaUnity/Plugins/Native/x64

For a simpler install, I have uploaded a version of the unity asset embedding the SOFA .dll files here: https://github.com/InfinyTech3D/SofaUnity-Renderer/releases/download/v22.12/SofaUnity-Renderer_v22.12_Win64.unitypackage

Best regards,

**Comment by CugAgo** [comment]
thanks for your help

**Comment by epernod** [comment]
This has been moved to a discussion to keep record
